using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using English_Quiz.Models;

namespace English_Quiz.DTO
{
    public class QuestionsAutoGenerateDTO
    {
        public System.Guid PR_KEY { get; set; }
        public Nullable<int> QUIZ_ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<int> TOTAL_QUESTION { get; set; }
        public Nullable<double> POINT_EACH_QS { get; set; }
        public Nullable<int> LIST_ORDER { get; set; }
        public string TYPE_NAME { get; set; }
        //public virtual English_Quiz.Models.Type Type { get; set; }
    }
}