//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evaluate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Evaluate()
        {
            this.History_Quiz = new HashSet<History_Quiz>();
        }
    
        public int EVALUATE_ID { get; set; }
        public string EVALUATE_DESCRIPTION { get; set; }
        public Nullable<int> FROM_POINT { get; set; }
        public Nullable<int> TO_POINT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<History_Quiz> History_Quiz { get; set; }
    }
}
