//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam_Class
    {
        public string EXAM_ID { get; set; }
        public int CLASS_ID { get; set; }
        public int EXAM_NUM { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Exam Exam { get; set; }
    }
}
