//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_Quiz
    {
        public System.Guid PR_KEY { get; set; }
        public string Quiz_ID { get; set; }
        public string User_Name { get; set; }
        public double Point { get; set; }
        public Nullable<System.DateTime> Date_Take_Quiz { get; set; }
        public string Quiz_Name { get; set; }
        public Nullable<int> EVALUATE_ID { get; set; }
    
        public virtual Evaluate Evaluate { get; set; }
    }
}
