//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listening_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Listening_Type()
        {
            this.Listenings = new HashSet<Listening>();
        }
    
        public int LISTENING_TYPE_ID { get; set; }
        public string LISTENING_TYPE_NAME_VN { get; set; }
        public string LISTENING_TYPE_NAME_EN { get; set; }
        public string DESCRIPTION_VN { get; set; }
        public string DESCRIPTION_EN { get; set; }
        public Nullable<int> ORDER_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Listening> Listenings { get; set; }
    }
}
