//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Listening
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Listening()
        {
            this.Questions = new HashSet<Question>();
            this.Quiz_Listening = new HashSet<Quiz_Listening>();
        }
    
        public string LISTENING_ID { get; set; }
        public string LISTENING_NAME_VN { get; set; }
        public string LISTENING_NAME_EN { get; set; }
        public Nullable<int> LISTENING_TYPE_ID { get; set; }
        public string LISTENING_FILE_NAME { get; set; }
        public bool IS_TEST { get; set; }
    
        public virtual Listening_Type Listening_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz_Listening> Quiz_Listening { get; set; }
    }
}
