//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class English_QuizEntities : DbContext
    {
        public English_QuizEntities()
            : base("name=English_QuizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<Exam_Class> Exam_Class { get; set; }
        public virtual DbSet<Exam_Information> Exam_Information { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<History_Quiz> History_Quiz { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Questions_Auto_Generate> Questions_Auto_Generate { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<Quiz_Level> Quiz_Level { get; set; }
        public virtual DbSet<Quiz_Questions> Quiz_Questions { get; set; }
        public virtual DbSet<Quiz_Type> Quiz_Type { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<User_Quiz_Question> User_Quiz_Question { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
