//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class English_QuizEntities : DbContext
    {
        public English_QuizEntities()
            : base("name=English_QuizEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Answer> Answers { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<EmployeeMaster> EmployeeMasters { get; set; }
        public virtual DbSet<Evaluate> Evaluates { get; set; }
        public virtual DbSet<Function> Functions { get; set; }
        public virtual DbSet<History_Quiz> History_Quiz { get; set; }
        public virtual DbSet<Listening> Listenings { get; set; }
        public virtual DbSet<Listening_Type> Listening_Type { get; set; }
        public virtual DbSet<Permission> Permissions { get; set; }
        public virtual DbSet<Question_Type> Question_Type { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Questions_Auto_Generate> Questions_Auto_Generate { get; set; }
        public virtual DbSet<Quiz> Quizs { get; set; }
        public virtual DbSet<Quiz_Listening> Quiz_Listening { get; set; }
        public virtual DbSet<Quiz_Questions> Quiz_Questions { get; set; }
        public virtual DbSet<Quiz_Reading> Quiz_Reading { get; set; }
        public virtual DbSet<Quiz_Type> Quiz_Type { get; set; }
        public virtual DbSet<Reading> Readings { get; set; }
        public virtual DbSet<Reading_Type> Reading_Type { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tip> Tips { get; set; }
        public virtual DbSet<Tip_Type> Tip_Type { get; set; }
        public virtual DbSet<User_Evaluate_Website> User_Evaluate_Website { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
