//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions_Auto_Generate
    {
        public System.Guid PR_KEY { get; set; }
        public int QUIZ_ID { get; set; }
        public int TYPE_ID { get; set; }
        public int TOTAL_QUESTION { get; set; }
        public double POINT_EACH_QS { get; set; }
        public int LIST_ORDER { get; set; }
    }
}
