//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Quiz_Questions = new HashSet<Quiz_Questions>();
            this.User_Quiz_Question = new HashSet<User_Quiz_Question>();
        }
    
        public string QUESTION_ID { get; set; }
        public string QUESTION_TEXT { get; set; }
        public Nullable<double> POINT { get; set; }
        public Nullable<int> LEVEL_ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Type Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz_Questions> Quiz_Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Quiz_Question> User_Quiz_Question { get; set; }
    }
}
