//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions_Auto_Generate
    {
        public System.Guid PR_KEY { get; set; }
        public string QUIZ_ID { get; set; }
        public Nullable<int> TYPE_ID { get; set; }
        public Nullable<int> TOTAL_QUESTION { get; set; }
        public Nullable<int> LIST_ORDER { get; set; }
    
        public virtual Question_Type Question_Type { get; set; }
    }
}
