//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Questions
    {
        public string QUIZ_ID { get; set; }
        public string QUESTION_ID { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<double> POINT { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Quiz Quiz { get; set; }
    }
}
