//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Quiz()
        {
            this.Quiz_Questions = new HashSet<Quiz_Questions>();
        }
    
        public string QUIZ_ID { get; set; }
        public string QUIZ_NAME { get; set; }
        public string QUIZ_TYPE_ID { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> TIME { get; set; }
        public string SOURCE_DESCRIPTION { get; set; }
        public string SOURCE_LINK { get; set; }
        public bool IS_TEST { get; set; }
        public Nullable<int> ORDER_NUMBER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Quiz_Questions> Quiz_Questions { get; set; }
        public virtual Quiz_Type Quiz_Type { get; set; }
    }
}
