//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quiz_Listening
    {
        public System.Guid PR_KEY { get; set; }
        public string QUIZ_ID { get; set; }
        public string LISTENING_ID { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
    
        public virtual Listening Listening { get; set; }
    }
}
