//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reading
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reading()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int READING_ID { get; set; }
        public string READING_TEXT { get; set; }
        public Nullable<int> READING_TYPE_ID { get; set; }
        public string READING_IMAGE { get; set; }
        public bool IS_IMAGE { get; set; }
        public bool IS_TEST { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Reading_Type Reading_Type { get; set; }
    }
}
