//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tip
    {
        public int TIP_ID { get; set; }
        public string TIP_NAME { get; set; }
        public string TIP_CONTENT { get; set; }
        public bool ACTIVE { get; set; }
        public Nullable<int> TIP_TYPE_ID { get; set; }
    
        public virtual Tip_Type Tip_Type { get; set; }
    }
}
