//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int USER_ID { get; set; }
        public string FULL_NAME { get; set; }
        public string PROFILE_IMAGE { get; set; }
        public string PASSWORD { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<int> PHONE_NUMBER { get; set; }
        public Nullable<int> ROLE_ID { get; set; }
        public string USER_NAME { get; set; }
        public bool IS_MANAGE { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
