//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace English_Quiz.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Evaluate_Website
    {
        public System.Guid PR_KEY { get; set; }
        public string USER_NAME_EVALUATE { get; set; }
        public string USER_JOB { get; set; }
        public string USER_CONTENT_EVALUATE { get; set; }
        public bool ACTIVE { get; set; }
    }
}
